### ISSUE TITLE
Possible issue on index.php

### ISSUE THREAD

**Issue by LosMyke** [awslabs/ecs-demo-php-simple-app#2]
Shouldn't line 31 contain "http:" ?

**Comment by euank** [comment]
All recent (including IE6 and lynx) browsers support "protocol relative urls", as described by [Paul Irish](http://www.paulirish.com/2010/the-protocol-relative-url/), so that should work fine!

Changing it to always be `https` would also be reasonable though.

If you're having trouble with it, please do reopen with any additional info.
Best,
Euan
